"""new fields in user model

Revision ID: 7325b8969444
Revises: 53e7cfd3eda3
Create Date: 2020-12-18 14:02:10.676865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325b8969444'
down_revision = '53e7cfd3eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
